name: CI ubuntu Build

on:
  push:
    branches:
      - '*'
    tags:
      - '**'
      
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04]
 
    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }}
        
    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
 
      - name: Install required packages
        run: |
          sudo apt install cmake make extra-cmake-modules libkf5syntaxhighlighting-dev libkf5syntaxhighlighting-data libkf5syntaxhighlighting-tools rpm libicu66 libicu-dev
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.12.8
          archives: 'qtbase qtmultimedia qtdeclarative qtquickcontrols2 qt'

      - name: Build QtAseman
        run: |
          git clone https://github.com/HamedMasafi/QtAseman.git
          cd QtAseman
          mkdir build
          cd build
          qmake ..
          make -j 4
          sudo make install
          
      - name: Build with CMake
        run: |
          mkdir build-cmake
          cd build-cmake
          cmake .. -DTRICKS_BUILD_DIR=build-cmake
          make -j 4
          VAR=`cat version`
          echo "version=${VAR}" >> $GITHUB_ENV
          
      - name: Build deb package
        run: |
          cd build-cmake
          sudo cpack -G DEB
          
      - name: Build rpm package
        run: |
          cd build-cmake
          sudo cpack -G RPM
  
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          gh release create $tag_name --generate-notes
          gh release upload $tag_name ./build-cmake/tricks.deb#tricks_${tag_name}_amd64-ubuntu-2004.deb
          gh release upload $tag_name ./build-cmake/tricks.rpm#tricks-${tag_name}-Linux-ubuntu-2004.rpm
