name: CI ubuntu Build

on:
  push:
    branches:
      - '*'
    tags:
      - '**'
      
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, ubuntu-20.04]
 
    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }}
        
    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
 
      - name: Install Qt from package manager
        run: |
          sudo apt update
          sudo apt install qt5-default qt5-qmake qt5-qmake-bin qtdeclarative5-dev libqt5core5a libqt5gui5 libqt5concurrent5 libqt5qml5 qtmultimedia5-dev libqt5multimedia5 libqt5multimedia5-plugins libqt5multimediaquick5 libqt5multimediawidgets5 libqt5multimediagsttools5 libqt5quick5 qml-module-qtquick2 qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-dialogs qml-module-qtquick-extras qml-module-qtquick-templates2 libqt5quickcontrols2-5 libqt5quicktemplates2-5 libqt5quickwidgets5 qtquickcontrols2-5-private-dev

      - name: Install required packages
        run: |
          sudo apt install cmake make extra-cmake-modules libkf5syntaxhighlighting-dev libkf5syntaxhighlighting-data libkf5syntaxhighlighting-tools rpm
          
      - name: Build QtAseman
        run: |
          git clone https://github.com/HamedMasafi/QtAseman.git
          cd QtAseman
          mkdir build
          cd build
          qmake ..
          make -j 4
          sudo make install
          
      - name: Build with CMake
        run: |
          mkdir build-cmake
          cd build-cmake
          cmake .. ${{ matrix.additional_arguments }}  ${{ matrix.cmake_params }} -DTRICKS_BUILD_DIR=build-cmake
          make -j 4
          VAR=`cat version`
          echo "version=${VAR}" >> $GITHUB_ENV
          
      - name: Build deb package
        run: |
          cd build-cmake
          sudo cpack -G DEB
          
      - name: Build rpm package
        run: |
          cd build-cmake
          sudo cpack -G RPM
  
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF##*/}"
          gh release create $tag_name --generate-notes
          gh release upload $tag_name ./build-cmake/tricks.deb#tricks_${tag_name}_amd64.deb
          gh release upload $tag_name ./build-cmake/tricks.rpm#tricks-${tag_name}-Linux.rpm
